### ISSUE TITLE
Rover mode, .pos file empty and no Sol: Lat: Lon: Alt: data

### ISSUE THREAD

**Issue by Church1182** [taroz/TouchRTKStation#6]
I've been working on adding a couple extra tabs to the program and ran into issue where I no longer get any solution data displayed in rover mode and the .pos file is empty save for the headers. No actual data.  The .ubx file saves and seems to be fine.
I'm using a pi3 B+ and I started with the [NEO-M8T from gnss.store](https://www.gnss.store/gnss-gps-modules/45-ublox-neo-m8t-time-raw-receiver-board-with-sma-rtk-ready.html?search_query=neo-m8t&results=67) and the unmodified program. In my final build I'm using the [waveshare HAT with the same ublox NEO-M8T chip](https://www.waveshare.com/neo-m8t-gnss-timing-hat.htm). At first I though it was just a config issue, but I've triple checked that the config is the same on all my M8T's and was working fine before. 

I have tried using the usb connected board from gnss.store and the unmodified program and still nothing.

Any ideas whats going on, or what to look at to figure it out?

The extra tab I added so far is just a tab with 3 buttons, Exit, Reboot, Shutdown.

**Comment by geofis** [comment]
Hello @Church1182 

I think you can perform a post-processing solution (PPK) to check if the receiver is working fine. To do so, convert the raw observations from the UBX file to RINEX format (using `convbin`) from both base and rover (I assume the receiver is configured to record raw observations).

If you don't have a base station on your own, you may be receiving corrections from a nearby base station, which hopefully stores observations in a server (i.e. FTP). Locate the file comprising the time span of the UBX file of the rover and convert them to RINEX format (`convbin` again).

With the raw observations from the base and the rover, you could try `rnx2rtkp` to perform a PPK solution. If you get solutions (Q=2 float or Q=1 fix), the receiver is working fine. If not, then you may need to check the configuration of the receiver, using u-center. You can also double-check the `.cmd` files of the repo to check if they are configured fine.

Good luck.

**Comment by Church1182** [comment]
Thanks for the advice, I will give that a try. I do have another unit setup at my shop that is running in base mode and there is an NGS NOAA CORS site 18.46 km from my shop. I ran three 24 hour collections a week apart and processed them with data from the CORS site to get 3 fixes that were the same to the 8th decimal. I was happy with that. 

I noticed that in Tho my on my Pi when I end the program the shell read out looks like this;
...
rtkrcv>
solution
rtkrcv>
malloc(): unsorted double linked list corrupted

From what I have found so far that appears to be a gcc related issue. Something with RTKLIB?

**Comment by geofis** [comment]
You're welcome.

I agree with you that it may be a gcc related issue. I am not familiar with the compilation process, but I faced a similar issue while trying to install RTKLIB alongside TouchRTKStation. I found that the new version of RTKLIB changed the main path for the apps, so the developer added a new directory inside the app directory. To solve this, before the installation, I added multiple symlinks inside the app directory pointing to the directories of the apps, such as:

```
ln -s /home/pi/RTKLIB/app/consapp/* /home/pi/RTKLIB/app/
```

You may find this change on line 31 of the `install/Install.sh` file of my forked repo [here](https://github.com/geofis/TouchRTKStation). In this file, you may also see that I use the forked repo [demo5](https://github.com/rtklibexplorer/RTKLIB), instead of the RTKLIB itself.

**Comment by Church1182** [comment]
I opted for editing the python file and finding the two lines where the program was trying to call rtkrcv or str2str and added the /app/ into the path. It seems to work fine, I just haven't figured out why it stopped displaying the information on the rover tab while it's running and populating the .pos file. The .ubx file is fine so far as I can tell. 
I've made my own fork to add the changes I've made.

**Comment by Church1182** [comment]
I went out yesterday and collected data with my rover and about 30 seconds in I got a Float and then Fix solution with position data. At this point I can only assume my previous instances were a lack of sufficient satellite signal to get a good fix. There does not seem to be an issue and I will close this.
